#SPDX-License-Identifier: MIT-0
---
# vars file for proto
# Additional configuration variables can be added here

proto_tools:
  - name: awscli
    version: "asdf:2.24.20"
  - name: go
    version: "1.24.1"
  - name: helm
    version: "asdf:3.17.1"
  - name: helmfile
    version: "asdf:1.0.0"
  - name: jq
    version: "asdf:1.7.1"
  - name: kubectl
    version: "asdf:1.32.2"
  - name: node
    version: "22.11.0"
  - name: proto
    version: "0.49.5"
  - name: pulumi
    version: "asdf:3.175.0"
  - name: python
    version: "3.10.11"
  - name: sops
    version: "asdf:3.10.2"
  - name: terraform
    version: "asdf:1.12.1"
  - name: deno
    version: "2.3.6"
  - name: dive
    version: "asdf:0.13.1"
